"""The student's decision log.

Wharton's rules: "You may not submit any work generated by an AI program as
your own." Every trade needs a Trading Note that Wharton audits, and the
deliverable instructions warn "You must use actual trading notes from trades
you made on WInS. (Yes, we will verify this.)"

So this module has exactly one job with respect to reasoning: capture it and
store it byte-for-byte. It supplies the surrounding facts — timestamp,
symbol, action, quantity, price, indicator values at decision time, which
constraints bound, and the data source — and nothing else. It never
generates, suggests, autocompletes, or templates the student's reasoning.

Append-only, JSONL, hash-chained so a later edit to a line is detectable.
"""

from __future__ import annotations

import hashlib
import json
from collections.abc import Mapping, Sequence
from dataclasses import dataclass, field
from datetime import UTC, date, datetime
from decimal import Decimal
from enum import Enum
from importlib import metadata as _importlib_metadata
from pathlib import Path

from investlab.contracts import Action, SizedOrder

TOOL_NAME = "investlab"


def tool_version() -> str:
    try:
        return _importlib_metadata.version(TOOL_NAME)
    except _importlib_metadata.PackageNotFoundError:
        return "0.0.0-dev"


class EntryKind(str, Enum):
    DECISION = "decision"
    CORRECTION = "correction"
    REVIEW = "review"


class EmptyReasoningError(ValueError):
    """Reasoning was blank. There is no default, placeholder, or template."""


@dataclass(frozen=True, slots=True)
class DecisionFacts:
    """The surrounding facts of one decision. Never the reasoning itself."""

    session: date
    symbol: str
    action: Action
    quantity: int
    price: Decimal
    indicators: Mapping[str, Decimal]
    binding_constraints: tuple[str, ...]
    data_source: str
    note_fields: Mapping[str, str] = field(default_factory=dict)


def facts_from_order(
    order: SizedOrder,
    session: date,
    indicators: Mapping[str, Decimal],
    data_source: str,
) -> DecisionFacts:
    """Assemble `DecisionFacts` from a `SizedOrder`. Facts only — no prose."""
    return DecisionFacts(
        session=session,
        symbol=order.symbol,
        action=order.action,
        quantity=order.quantity,
        price=order.price_bound,
        indicators=dict(indicators),
        binding_constraints=(order.binding_constraint,),
        data_source=data_source,
    )


@dataclass(frozen=True, slots=True)
class JournalEntry:
    entry_id: str
    kind: EntryKind
    recorded_at: datetime
    facts: DecisionFacts
    reasoning: str
    author: str
    corrects: str | None
    tool_name: str
    tool_version: str
    prev_hash: str
    entry_hash: str


def _facts_to_dict(facts: DecisionFacts) -> dict:
    return {
        "session": facts.session.isoformat(),
        "symbol": facts.symbol,
        "action": facts.action.value,
        "quantity": facts.quantity,
        "price": str(facts.price),
        "indicators": {k: str(v) for k, v in facts.indicators.items()},
        "binding_constraints": list(facts.binding_constraints),
        "data_source": facts.data_source,
        "note_fields": dict(facts.note_fields),
    }


def _facts_from_dict(d: dict) -> DecisionFacts:
    return DecisionFacts(
        session=date.fromisoformat(d["session"]),
        symbol=d["symbol"],
        action=Action(d["action"]),
        quantity=d["quantity"],
        price=Decimal(d["price"]),
        indicators={k: Decimal(v) for k, v in d["indicators"].items()},
        binding_constraints=tuple(d["binding_constraints"]),
        data_source=d["data_source"],
        note_fields=dict(d.get("note_fields", {})),
    )


def _hash_payload(payload: dict) -> str:
    canonical = json.dumps(payload, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


class Journal:
    """Append-only, hash-chained JSONL log of student-authored reasoning.

    Every write opens the file in append mode and writes exactly one JSON
    line. There is no update path and no delete path: a correction is a new
    entry whose `corrects` field names the original, which stays in the
    file forever.
    """

    def __init__(self, path: Path) -> None:
        self._path = Path(path)

    def entries(self) -> tuple[JournalEntry, ...]:
        if not self._path.exists():
            return ()
        result: list[JournalEntry] = []
        for line in self._path.read_text().splitlines():
            if not line.strip():
                continue
            payload = json.loads(line)
            result.append(
                JournalEntry(
                    entry_id=payload["entry_id"],
                    kind=EntryKind(payload["kind"]),
                    recorded_at=datetime.fromisoformat(payload["recorded_at"]),
                    facts=_facts_from_dict(payload["facts"]),
                    reasoning=payload["reasoning"],
                    author=payload["author"],
                    corrects=payload["corrects"],
                    tool_name=payload["tool_name"],
                    tool_version=payload["tool_version"],
                    prev_hash=payload["prev_hash"],
                    entry_hash=payload["entry_hash"],
                )
            )
        return tuple(result)

    def record(
        self,
        facts: DecisionFacts,
        reasoning: str,
        *,
        author: str = "student",
        kind: EntryKind = EntryKind.DECISION,
        recorded_at: datetime | None = None,
    ) -> JournalEntry:
        """Store `reasoning` exactly as passed. Not stripped, not
        normalized, not capitalized, not generated. Raises
        `EmptyReasoningError` before anything is written if it is blank."""
        if not reasoning.strip():
            raise EmptyReasoningError(
                "reasoning must be the student's own words; it is never defaulted"
            )
        return self._append(
            kind=kind,
            facts=facts,
            reasoning=reasoning,
            author=author,
            corrects=None,
            recorded_at=recorded_at,
        )

    def amend(
        self,
        entry_id: str,
        reasoning: str,
        *,
        author: str = "student",
        recorded_at: datetime | None = None,
    ) -> JournalEntry:
        """Append a `CORRECTION` entry referencing `entry_id`. The original
        entry is never edited or removed."""
        if not reasoning.strip():
            raise EmptyReasoningError(
                "reasoning must be the student's own words; it is never defaulted"
            )
        existing = {e.entry_id: e for e in self.entries()}
        if entry_id not in existing:
            raise KeyError(f"unknown journal entry {entry_id!r}")
        original = existing[entry_id]
        return self._append(
            kind=EntryKind.CORRECTION,
            facts=original.facts,
            reasoning=reasoning,
            author=author,
            corrects=entry_id,
            recorded_at=recorded_at,
        )

    def _append(
        self,
        *,
        kind: EntryKind,
        facts: DecisionFacts,
        reasoning: str,
        author: str,
        corrects: str | None,
        recorded_at: datetime | None,
    ) -> JournalEntry:
        existing = self.entries()
        entry_id = f"JE-{len(existing) + 1:06d}"
        prev_hash = existing[-1].entry_hash if existing else ""
        at = recorded_at if recorded_at is not None else datetime.now(UTC)

        payload = {
            "entry_id": entry_id,
            "kind": kind.value,
            "recorded_at": at.isoformat(),
            "facts": _facts_to_dict(facts),
            "reasoning": reasoning,
            "author": author,
            "corrects": corrects,
            "tool_name": TOOL_NAME,
            "tool_version": tool_version(),
            "prev_hash": prev_hash,
        }
        entry_hash = _hash_payload(payload)
        payload["entry_hash"] = entry_hash

        self._path.parent.mkdir(parents=True, exist_ok=True)
        with self._path.open("a", encoding="utf-8") as f:
            f.write(json.dumps(payload) + "\n")

        return JournalEntry(
            entry_id=entry_id,
            kind=kind,
            recorded_at=at,
            facts=facts,
            reasoning=reasoning,
            author=author,
            corrects=corrects,
            tool_name=TOOL_NAME,
            tool_version=tool_version(),
            prev_hash=prev_hash,
            entry_hash=entry_hash,
        )

    def verify_chain(self) -> bool:
        """Re-derive the hash chain from the file on disk. False if any
        line was edited after the fact."""
        if not self._path.exists():
            return True
        prev_hash = ""
        for line in self._path.read_text().splitlines():
            if not line.strip():
                continue
            payload = json.loads(line)
            stored_hash = payload.pop("entry_hash", None)
            if payload.get("prev_hash") != prev_hash:
                return False
            if _hash_payload(payload) != stored_hash:
                return False
            prev_hash = stored_hash
        return True


def export_evidence_packet(
    entries: Sequence[JournalEntry],
    *,
    data_sources: Sequence[str],
    generated_at: datetime,
) -> str:
    """Assemble entries into an evidence packet: facts plus the student's
    own reasoning quoted verbatim, with a provenance footer naming the
    tool, version, and data sources so it can be cited in APA. The packet's
    own words are headings, field labels, and numbers — no narrative, no
    summary, no synthesis."""
    lines: list[str] = ["# Trading Journal Evidence Packet", ""]

    for entry in entries:
        lines.append(f"## {entry.entry_id} — {entry.facts.symbol} ({entry.kind.value})")
        lines.append("")
        lines.append("| Field | Value |")
        lines.append("|---|---|")
        lines.append(f"| Session | {entry.facts.session.isoformat()} |")
        lines.append(f"| Symbol | {entry.facts.symbol} |")
        lines.append(f"| Action | {entry.facts.action.value} |")
        lines.append(f"| Quantity | {entry.facts.quantity} |")
        lines.append(f"| Price | {entry.facts.price} |")
        for name, value in entry.facts.indicators.items():
            lines.append(f"| {name} | {value} |")
        lines.append(f"| Binding constraints | {', '.join(entry.facts.binding_constraints)} |")
        lines.append(f"| Data source | {entry.facts.data_source} |")
        lines.append(f"| Recorded at | {entry.recorded_at.isoformat()} |")
        lines.append(f"| Author | {entry.author} |")
        if entry.corrects:
            lines.append(f"| Corrects | {entry.corrects} |")
        lines.append("")
        lines.append(f"### Student-authored reasoning ({entry.author})")
        lines.append("")
        lines.append("> " + entry.reasoning.replace("\n", "\n> "))
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("## Provenance")
    lines.append("")
    lines.append(f"- Tool: {TOOL_NAME} {tool_version()}")
    lines.append(f"- Data sources: {', '.join(data_sources)}")
    lines.append(f"- Generated at: {generated_at.isoformat()}")
    lines.append(
        f"- Citation (APA): {TOOL_NAME} ({generated_at.year}). "
        f"{TOOL_NAME} (Version {tool_version()}) [Computer software]."
    )

    return "\n".join(lines)
