"""Wharton Investment Network Simulation (WInS) competition profile.

The 2026-27 Wharton trading rules are not released until 2026-09-15. This
module therefore has two states:

- `SeasonStatus.WHARTON_UNVERIFIED` (the default): no 2026-27 config has been
  loaded. Every dollar figure and list shown is PROVISIONAL, carried over
  from the 2025-26 season (see `docs/rules/wharton-verified.md`). ETFs are
  blocked outright because the Approved ETF List does not exist yet.
  `check_rules` reports exactly what is missing and names 2026-09-15.
  `build_daily_plan` refuses to emit an actionable order sheet, though
  eligibility screening keeps running.
- `SeasonStatus.WHARTON_VERIFIED`: reached by loading a `WhartonSeasonConfig`
  (via `load_season_config` + `WhartonProfile.with_season`) once a student
  has transcribed the 2026-09-15 materials.

AI-authorship constraint (Wharton: "You may not submit any work generated by
an AI program as your own"; trading notes are audited). This module emits
only facts, numbers, constraint results, and rule status. It never
generates an investment thesis, trading-note text, Investment Policy
Statement prose, or any other narrative a student would submit. Where a
config field is transcribed by a student verbatim (`client_mandate_summary`)
this module stores and echoes it; it never writes or edits it.

Money is always `decimal.Decimal`. A `float` literal in a money path here is
a defect. Imports: `investlab.contracts` and the standard library only.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field, replace
from datetime import date
from decimal import ROUND_HALF_UP, Decimal, InvalidOperation
from enum import Enum
from pathlib import Path
from typing import ClassVar

from investlab.contracts import (
    AccountState,
    AssetClass,
    Bar,
    BlockedOrder,
    BlockReason,
    DailyPlan,
    Instrument,
    RuleCheck,
    RuleStatus,
    SizedOrder,
    SizingConstraints,
)

# --------------------------------------------------------------------------
# Provisional constants (2025-26 season -- NOT confirmed for 2026-27)
# --------------------------------------------------------------------------

# Starting capital was $500,000 last season. The $100,000 figure that shows
# up in secondary sources is StockTrak's generic platform FAQ boilerplate,
# not the Wharton competition rule. Never default to it.
PROVISIONAL_STARTING_CAPITAL = Decimal("500000")
MISREPORTED_STARTING_CAPITAL = Decimal("100000")

PROVISIONAL_STOCK_COMMISSION = Decimal("25")
PROVISIONAL_TREASURY_COMMISSION = Decimal("10")
PROVISIONAL_MIN_SHARE_PRICE = Decimal("5")

HARD_TRADE_CAP = 200
SELF_IMPOSED_TRADE_BUDGET = 40
SELF_IMPOSED_POSITION_CEILING = Decimal("0.20")
SELF_IMPOSED_RISK_FRACTION = Decimal("0.01")

# Confirmed 2026-27 dates (StockTrak / SurveyMonkey Apply materials).
MATERIALS_RELEASE = date(2026, 9, 15)
TRADING_BEGINS = date(2026, 9, 28)
# Named to avoid the substring "ips" (Investment Policy Statement), which is
# a banned fragment in the module's own AI-authorship self-check further
# down this file (`test_module_emits_no_submittable_prose` mirrors this).
INVESTMENT_POLICY_STATEMENT_DUE = date(2026, 11, 6)
FINAL_REPORT_DUE = date(2026, 12, 4)

# Prior-season shape for "minimum trading activity by early October";
# PROVISIONAL until a verified config supplies the real 2026-27 date.
PROVISIONAL_ACTIVITY_DEADLINE = date(2026, 10, 9)


def provisional_disclosures() -> tuple[str, ...]:
    """Human-readable labels for every PROVISIONAL prior-season figure.

    Joined together these must always mention "PROVISIONAL", the 2025-26
    season, and the real $500,000 starting-capital figure -- the module's
    own defense against silently treating a prior-season guess as fact.
    """
    return (
        (
            "PROVISIONAL (2025-26 season, not yet confirmed for 2026-27): "
            "starting capital $500,000. The commonly cited $100,000 figure is "
            "StockTrak's generic platform FAQ boilerplate and is wrong for this "
            "competition."
        ),
        (
            "PROVISIONAL (2025-26 season, not yet confirmed for 2026-27): "
            "commissions $25 per stock trade, $10 per treasury bond trade."
        ),
        (
            "PROVISIONAL (2025-26 season, not yet confirmed for 2026-27): "
            "minimum share price $5.00, 200-trade season cap."
        ),
    )


# --------------------------------------------------------------------------
# Season verification state
# --------------------------------------------------------------------------


class SeasonStatus(str, Enum):
    WHARTON_UNVERIFIED = "wharton_unverified"
    WHARTON_VERIFIED = "wharton_verified"


class WhartonConfigError(ValueError):
    """A `WhartonSeasonConfig` file failed validation."""


_CONFIG_KEYS: frozenset[str] = frozenset(
    {
        "starting_capital",
        "approved_etfs",
        "position_ceiling_fraction",
        "minimum_activity_deadline",
        "client_mandate_summary",
    }
)


@dataclass(frozen=True, slots=True)
class WhartonSeasonConfig:
    """The 2026-27 season parameters, transcribed by a student from the
    materials released 2026-09-15.

    `client_mandate_summary` is transcribed by the student from the Wharton
    case study. This module stores and echoes that string; it never
    generates or edits it -- doing so would be exactly the kind of
    submittable prose Wharton's AI policy prohibits this tool from
    producing.
    """

    starting_capital: Decimal
    approved_etfs: frozenset[str]
    position_ceiling_fraction: Decimal
    minimum_activity_deadline: date
    client_mandate_summary: str
    source: str = "inline"

    def __post_init__(self) -> None:
        if self.starting_capital <= 0:
            raise WhartonConfigError("starting_capital must be a positive amount")
        if not self.approved_etfs:
            raise WhartonConfigError("approved_etfs must contain at least one approved ticker")
        if not (Decimal("0") < self.position_ceiling_fraction <= Decimal("1")):
            raise WhartonConfigError(
                "position_ceiling_fraction must be between 0 (exclusive) and 1 (inclusive)"
            )
        if not self.client_mandate_summary or not self.client_mandate_summary.strip():
            raise WhartonConfigError("client_mandate_summary must not be blank")


def _config_from_mapping(data: object, source: str) -> WhartonSeasonConfig:
    if not isinstance(data, dict):
        raise WhartonConfigError(f"{source}: config must be a mapping of the five required keys")

    unknown = set(data) - _CONFIG_KEYS
    if unknown:
        raise WhartonConfigError(
            f"{source}: unknown key(s) {sorted(unknown)}; expected {sorted(_CONFIG_KEYS)}"
        )
    missing = _CONFIG_KEYS - set(data)
    if missing:
        raise WhartonConfigError(f"{source}: missing required key(s) {sorted(missing)}")

    try:
        starting_capital = Decimal(str(data["starting_capital"]))
    except (InvalidOperation, TypeError, ValueError) as exc:
        raise WhartonConfigError(
            f"{source}: starting_capital is not a valid decimal amount"
        ) from exc

    etfs_raw = data["approved_etfs"]
    if not isinstance(etfs_raw, (list, tuple)) or not all(isinstance(s, str) for s in etfs_raw):
        raise WhartonConfigError(f"{source}: approved_etfs must be a list of ticker strings")
    approved_etfs = frozenset(s.strip().upper() for s in etfs_raw if s.strip())

    try:
        position_ceiling_fraction = Decimal(str(data["position_ceiling_fraction"]))
    except (InvalidOperation, TypeError, ValueError) as exc:
        raise WhartonConfigError(
            f"{source}: position_ceiling_fraction is not a valid decimal fraction"
        ) from exc

    try:
        minimum_activity_deadline = date.fromisoformat(str(data["minimum_activity_deadline"]))
    except ValueError as exc:
        raise WhartonConfigError(
            f"{source}: minimum_activity_deadline must be an ISO date (YYYY-MM-DD)"
        ) from exc

    client_mandate_summary = data["client_mandate_summary"]
    if not isinstance(client_mandate_summary, str):
        raise WhartonConfigError(f"{source}: client_mandate_summary must be a string")

    return WhartonSeasonConfig(
        starting_capital=starting_capital,
        approved_etfs=approved_etfs,
        position_ceiling_fraction=position_ceiling_fraction,
        minimum_activity_deadline=minimum_activity_deadline,
        client_mandate_summary=client_mandate_summary.strip(),
        source=source,
    )


def _unquote(value: str) -> str:
    if len(value) >= 2 and value[0] == value[-1] and value[0] in ("'", '"'):
        return value[1:-1]
    return value


def _parse_restricted_yaml(text: str) -> dict[str, object]:
    """A hand-written parser for a deliberately narrow YAML subset: flat
    `key: value` pairs, `key:` followed by `  - item` list lines, `#`
    comments, and quoted scalars. PyYAML is not a project dependency, so
    this is not general YAML -- anything outside that shape raises
    `WhartonConfigError` naming the offending line rather than guessing.
    """
    result: dict[str, object] = {}
    current_list_key: str | None = None
    current_list: list[str] = []

    def flush_list() -> None:
        nonlocal current_list_key, current_list
        if current_list_key is not None:
            result[current_list_key] = current_list
            current_list_key = None
            current_list = []

    for lineno, raw_line in enumerate(text.splitlines(), start=1):
        stripped = raw_line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if stripped.startswith("- "):
            if current_list_key is None:
                raise WhartonConfigError(f"line {lineno}: list item with no preceding 'key:'")
            current_list.append(_unquote(stripped[2:].strip()))
            continue
        if ":" not in stripped:
            raise WhartonConfigError(f"line {lineno}: expected 'key: value', got {raw_line!r}")
        key, _, value = stripped.partition(":")
        key = key.strip()
        value = value.strip()
        if not key or not key.replace("_", "").isalnum():
            raise WhartonConfigError(f"line {lineno}: invalid key {key!r}")
        flush_list()
        if value == "":
            current_list_key = key
            current_list = []
        else:
            result[key] = _unquote(value)
    flush_list()
    return result


def load_season_config(path: str | Path) -> WhartonSeasonConfig:
    """Load a `WhartonSeasonConfig` from JSON or the restricted YAML subset
    supported by `_parse_restricted_yaml`, dispatching on file suffix.

    JSON is parsed with `parse_float=Decimal` so a money value never passes
    through a Python `float` on its way into a `Decimal`.
    """
    p = Path(path)
    text = p.read_text()
    suffix = p.suffix.lower()
    if suffix == ".json":
        try:
            data = json.loads(text, parse_float=Decimal)
        except json.JSONDecodeError as exc:
            raise WhartonConfigError(f"{p}: invalid JSON ({exc})") from exc
    elif suffix in (".yaml", ".yml"):
        data = _parse_restricted_yaml(text)
    else:
        raise WhartonConfigError(f"{p}: unsupported config format {suffix!r}; use .json or .yaml")
    return _config_from_mapping(data, source=str(p))


def season_config_template() -> str:
    """A fill-in-the-blanks JSON template for the five `WhartonSeasonConfig`
    keys, meant to be copied and edited once the 2026-09-15 materials are
    out. Values are placeholders, not this module's guesses.
    """
    return (
        "{\n"
        '  "starting_capital": "REPLACE_WITH_2026_27_STARTING_CAPITAL",\n'
        '  "approved_etfs": ["REPLACE", "WITH", "THE", "APPROVED", "ETF", "LIST"],\n'
        '  "position_ceiling_fraction": "0.15",\n'
        '  "minimum_activity_deadline": "REPLACE_WITH_DEADLINE_FROM_MATERIALS",\n'
        '  "client_mandate_summary": "Transcribe the client mandate from the '
        '2026-09-15 case study here, in your own words."\n'
        "}\n"
    )


# --------------------------------------------------------------------------
# Trade budget
# --------------------------------------------------------------------------


class BudgetSeverity(str, Enum):
    OK = "ok"
    NOTICE = "notice"
    WARNING = "warning"
    CRITICAL = "critical"
    BLOCKED = "blocked"


_DRAG_FRACTION_QUANT = Decimal("1e-8")
_DRAG_PCT_QUANT = Decimal("1e-6")
_CRITICAL_WINDOW = 10  # trades before hard_cap where severity becomes CRITICAL


@dataclass(frozen=True, slots=True)
class TradeBudget:
    """Tracks season trade usage against a self-imposed budget and the
    200-trade hard cap. Every buy and every sell counts as one trade.

    Severity ladder: OK under 30, NOTICE 30-39, WARNING at the self-imposed
    budget (40) through 189 (still legal -- Wharton is not a trading game,
    but nothing prohibits it yet), CRITICAL in the last 10 trades before the
    hard cap, BLOCKED at the hard cap. Only BLOCKED produces
    `satisfied=False`; a warning must stay `satisfied=True` or it would
    silently kill the order sheet through `DailyPlan.is_actionable`.
    """

    trades_used: int = 0
    self_imposed_budget: int = SELF_IMPOSED_TRADE_BUDGET
    hard_cap: int = HARD_TRADE_CAP
    commission_per_trade: Decimal = PROVISIONAL_STOCK_COMMISSION

    def __post_init__(self) -> None:
        if self.trades_used < 0:
            raise ValueError("trades_used cannot be negative")

    @property
    def remaining_self_imposed(self) -> int:
        return max(0, self.self_imposed_budget - self.trades_used)

    @property
    def remaining_hard_cap(self) -> int:
        return max(0, self.hard_cap - self.trades_used)

    @property
    def commission_spent(self) -> Decimal:
        return self.commission_per_trade * Decimal(self.trades_used)

    @property
    def commission_at_self_imposed_budget(self) -> Decimal:
        return self.commission_per_trade * Decimal(self.self_imposed_budget)

    @property
    def commission_at_hard_cap(self) -> Decimal:
        return self.commission_per_trade * Decimal(self.hard_cap)

    @property
    def severity(self) -> BudgetSeverity:
        if self.trades_used >= self.hard_cap:
            return BudgetSeverity.BLOCKED
        if self.trades_used >= self.hard_cap - _CRITICAL_WINDOW:
            return BudgetSeverity.CRITICAL
        if self.trades_used >= self.self_imposed_budget:
            return BudgetSeverity.WARNING
        if self.trades_used >= 30:
            return BudgetSeverity.NOTICE
        return BudgetSeverity.OK

    @property
    def is_exhausted(self) -> bool:
        return self.trades_used >= self.hard_cap

    def can_trade(self, n: int = 1) -> bool:
        return self.trades_used + n <= self.hard_cap

    def with_trades(self, n: int) -> TradeBudget:
        return replace(self, trades_used=self.trades_used + n)

    def commission_drag_fraction(self, equity: Decimal) -> Decimal:
        """Commission spent so far as a fraction of `equity`."""
        if equity <= 0:
            raise ValueError("equity must be positive to compute commission drag")
        return (self.commission_spent / equity).quantize(
            _DRAG_FRACTION_QUANT, rounding=ROUND_HALF_UP
        )

    def commission_drag_pct(self, equity: Decimal) -> Decimal:
        """Commission spent so far as a percentage of `equity`."""
        return (self.commission_drag_fraction(equity) * Decimal(100)).quantize(
            _DRAG_PCT_QUANT, rounding=ROUND_HALF_UP
        )

    def to_rule_check(self, equity: Decimal) -> RuleCheck:
        sev = self.severity
        if sev is BudgetSeverity.BLOCKED:
            detail = (
                f"BLOCKED: {self.trades_used} trades used meets or exceeds the "
                f"hard cap of {self.hard_cap} (PROVISIONAL, 2025-26 season). No "
                "further trades may be entered this season."
            )
            return RuleCheck("trade_budget", RuleStatus.VERIFIED, False, detail)
        if sev is BudgetSeverity.CRITICAL:
            detail = (
                f"CRITICAL: {self.trades_used} of {self.hard_cap} trades used "
                f"(PROVISIONAL hard cap); only {self.remaining_hard_cap} remain "
                "this season."
            )
        elif sev is BudgetSeverity.WARNING:
            detail = (
                f"WARNING: {self.trades_used} trades used, past the self-imposed "
                f"budget of {self.self_imposed_budget} (hard cap {self.hard_cap}, "
                "PROVISIONAL). This is not a trading game -- Wharton judges "
                "reward a low-turnover, thesis-driven portfolio, not activity."
            )
        elif sev is BudgetSeverity.NOTICE:
            detail = (
                f"NOTICE: {self.trades_used} trades used, approaching the "
                f"self-imposed budget of {self.self_imposed_budget} "
                f"(hard cap {self.hard_cap}, PROVISIONAL)."
            )
        else:
            detail = (
                f"OK: {self.trades_used} of {self.self_imposed_budget} "
                f"self-imposed trade budget used (hard cap {self.hard_cap}, "
                "PROVISIONAL)."
            )
        if equity > 0:
            detail += f" Commission spent so far: ${self.commission_spent:,.2f}."
        return RuleCheck("trade_budget", RuleStatus.VERIFIED, True, detail)

    def blocked_order(self, symbol: str) -> BlockedOrder:
        return BlockedOrder(
            symbol,
            BlockReason.TRADE_BUDGET_EXHAUSTED,
            f"{symbol}: trade budget exhausted ({self.trades_used}/{self.hard_cap} "
            "trades used this season, PROVISIONAL 2025-26 hard cap).",
        )


# --------------------------------------------------------------------------
# WhartonProfile
# --------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class WhartonProfile:
    """A `CompetitionProfile` for the Wharton Investment Network Simulation.

    Two states, encoded by whether `season` is set:

    - `WHARTON_UNVERIFIED` (`season is None`, the default): the 2026-27
      trading rules have not been released. Prior-season (2025-26) values
      load as PROVISIONAL. `check_rules` reports exactly what is missing
      and names the 2026-09-15 release date. `evaluate`/`is_eligible` still
      run -- research screening never stops -- but every ETF is blocked
      pending the Approved ETF List, and `build_daily_plan` withholds every
      order rather than emit an actionable sheet under unread rules.
    - `WHARTON_VERIFIED` (`season` set via `with_season`): a
      `WhartonSeasonConfig` supplies 2026-27 starting capital, the Approved
      ETF List, the position ceiling, the minimum-activity deadline, and
      the client mandate summary.
    """

    season: WhartonSeasonConfig | None = None
    budget: TradeBudget = field(default_factory=TradeBudget)

    name: ClassVar[str] = "wharton"
    display_name: ClassVar[str] = "Wharton Investment Network Simulation (WInS)"
    allows_margin: ClassVar[bool] = False
    allows_shorting: ClassVar[bool] = False
    commission_per_trade: ClassVar[Decimal] = PROVISIONAL_STOCK_COMMISSION
    treasury_commission_per_trade: ClassVar[Decimal] = PROVISIONAL_TREASURY_COMMISSION
    min_share_price: ClassVar[Decimal] = PROVISIONAL_MIN_SHARE_PRICE

    # -- identity / state ---------------------------------------------------

    @property
    def status(self) -> SeasonStatus:
        return SeasonStatus.WHARTON_VERIFIED if self.season else SeasonStatus.WHARTON_UNVERIFIED

    @property
    def is_verified(self) -> bool:
        return self.season is not None

    @property
    def starting_cash(self) -> Decimal:
        return self.season.starting_capital if self.season else PROVISIONAL_STARTING_CAPITAL

    @property
    def starting_cash_is_provisional(self) -> bool:
        return self.season is None

    @property
    def position_ceiling_fraction(self) -> Decimal:
        return (
            self.season.position_ceiling_fraction if self.season else SELF_IMPOSED_POSITION_CEILING
        )

    # -- state transitions ---------------------------------------------------

    def with_season(self, season: WhartonSeasonConfig) -> WhartonProfile:
        return replace(self, season=season)

    def with_trade_budget(self, budget: TradeBudget) -> WhartonProfile:
        return replace(self, budget=budget)

    # -- eligibility ----------------------------------------------------------

    def evaluate(self, instrument: Instrument, bar: Bar) -> BlockedOrder | None:
        """Check order, first match wins, chosen so the reported reason is
        the most fundamental one: commodity/crypto trust -> leveraged/
        inverse -> unsupported asset class -> missing exchange -> ETF
        approval -> bond approval -> price floor.
        """
        symbol = instrument.symbol

        if instrument.is_commodity_or_crypto_trust:
            grounds = ["explicitly prohibited: crypto and commodity trusts are banned outright"]
            if instrument.asset_class is AssetClass.ETF:
                grounds.append(
                    "ETFs are eligible only from the Approved ETF List, which this "
                    "instrument is not on"
                )
            if len(grounds) > 1:
                detail = (
                    f"{symbol} is rejected on two independent grounds: "
                    f"(1) {grounds[0]}; (2) {grounds[1]}."
                )
            else:
                detail = f"{symbol} is rejected: {grounds[0]}."
            return BlockedOrder(symbol, BlockReason.PROHIBITED_SECURITY, detail)

        if instrument.is_leveraged:
            return BlockedOrder(
                symbol,
                BlockReason.PROHIBITED_SECURITY,
                f"{symbol} is a leveraged/inverse product; Wharton prohibits "
                "derivatives and leveraged instruments.",
            )

        # `AssetClass` has no DERIVATIVE member, so a true option or future
        # cannot reach this function at all; leveraged/inverse products are
        # the closest representable proxy and are rejected above. This
        # check is written as an allow-list (stock/ETF/bond only) rather
        # than a deny-list, so any future AssetClass member is rejected by
        # default instead of silently passing through.
        if instrument.asset_class not in (AssetClass.STOCK, AssetClass.ETF, AssetClass.BOND):
            return BlockedOrder(
                symbol,
                BlockReason.PROHIBITED_SECURITY,
                f"{symbol} is a {instrument.asset_class.value}, not an eligible "
                "Wharton asset class (stock, ETF, or treasury bond).",
            )

        if not instrument.exchange:
            return BlockedOrder(
                symbol,
                BlockReason.INELIGIBLE_EXCHANGE,
                f"{symbol} has no listed exchange; Wharton requires a platform-supported exchange.",
            )

        if instrument.asset_class is AssetClass.ETF:
            if self.season is None:
                return BlockedOrder(
                    symbol,
                    BlockReason.UNVERIFIED_INSTRUMENT,
                    f"{symbol}: the Approved ETF List is not yet known. It "
                    f"arrives with the {MATERIALS_RELEASE.isoformat()} materials "
                    "release; until then every ETF is blocked.",
                )
            if symbol not in self.season.approved_etfs:
                return BlockedOrder(
                    symbol,
                    BlockReason.PROHIBITED_SECURITY,
                    f"{symbol} is not on the Approved ETF List for the 2026-27 season.",
                )

        # Treasury bonds are also drawn from an approved list per the rules,
        # but that list is optional and is not one of the five
        # WhartonSeasonConfig keys this profile carries -- see the report
        # for this observation. Bonds are accepted here subject only to the
        # price floor below.

        if bar.close < self.min_share_price:
            return BlockedOrder(
                symbol,
                BlockReason.PRICE_BELOW_MINIMUM,
                f"{symbol} at ${bar.close} is below the PROVISIONAL $5 minimum share price.",
            )

        return None

    def is_eligible(self, instrument: Instrument, bar: Bar) -> tuple[bool, str]:
        blocked = self.evaluate(instrument, bar)
        if blocked is None:
            return True, ""
        return False, blocked.detail

    # -- sizing -----------------------------------------------------------

    def sizing_constraints(self, account: AccountState) -> SizingConstraints:
        return SizingConstraints(
            equity=account.equity,
            spendable_cash=account.cash,  # margin banned: cash only, never buying power
            risk_fraction=SELF_IMPOSED_RISK_FRACTION,
            position_ceiling_fraction=self.position_ceiling_fraction,
            min_shares=1,
            min_price=self.min_share_price,
            commission_per_trade=self.commission_per_trade,
            sell_fee_rate=Decimal("0"),
        )

    # -- rule checks --------------------------------------------------------

    def check_rules(self, account: AccountState, today: date) -> list[RuleCheck]:
        checks: list[RuleCheck] = []

        if self.season is None:
            missing = (
                "starting capital, the Approved ETF List, the client mandate, "
                "position limits, and the minimum trading activity deadline"
            )
            checks.append(
                RuleCheck(
                    "season_materials_verified",
                    RuleStatus.INCOMPLETE,
                    False,
                    (
                        "2026-27 Wharton trading rules are not yet released "
                        f"(materials arrive {MATERIALS_RELEASE.isoformat()}). "
                        f"Missing: {missing}. Values shown are PROVISIONAL, "
                        "carried over from the 2025-26 season. Starting capital "
                        f"defaults to $500,000, PROVISIONAL -- NOT the "
                        f"${MISREPORTED_STARTING_CAPITAL:,} figure in "
                        "StockTrak's boilerplate FAQ, which is wrong for this "
                        "competition."
                    ),
                    deadline=MATERIALS_RELEASE,
                )
            )
            checks.append(
                RuleCheck(
                    "trading_rules_loaded",
                    RuleStatus.VERIFIED,
                    False,
                    (
                        "No order sheet can be marked actionable until a "
                        "WhartonSeasonConfig for 2026-27 is loaded with "
                        "`with_season`. This is a confirmed rule: do not trade "
                        "under season parameters that have not been read."
                    ),
                )
            )
        else:
            checks.append(
                RuleCheck(
                    "season_materials_verified",
                    RuleStatus.VERIFIED,
                    True,
                    f"2026-27 season config loaded from {self.season.source}.",
                )
            )
            checks.append(
                RuleCheck(
                    "trading_rules_loaded",
                    RuleStatus.VERIFIED,
                    True,
                    "2026-27 trading rules loaded; order sheet may be actionable.",
                )
            )

        checks.append(self._approved_etf_minimum_check(account))
        checks.append(self.budget.to_rule_check(account.equity))
        checks.append(self._minimum_trading_activity_check(today))
        checks.append(self._commission_drag_check(account))
        checks.append(self._margin_and_shorting_check(account))
        checks.append(
            RuleCheck(
                "student_authorship",
                RuleStatus.VERIFIED,
                True,
                (
                    "Wharton requires original student work: trading notes, "
                    "the Investment Policy Statement, and the investment "
                    "thesis must be written by the student, not generated by "
                    "this tool. Any AI assistance used must be cited in APA in "
                    "the Works Cited. This module emits only facts, numbers, "
                    "and rule status."
                ),
            )
        )

        return checks

    def _approved_etf_minimum_check(self, account: AccountState) -> RuleCheck:
        if self.season is None:
            return RuleCheck(
                "approved_etf_minimum",
                RuleStatus.INCOMPLETE,
                False,
                (
                    "Cannot verify the at-least-one-approved-ETF requirement: "
                    f"the Approved ETF List has not been released (arrives "
                    f"{MATERIALS_RELEASE.isoformat()})."
                ),
            )
        held_symbols = {pos.symbol for pos in account.positions if pos.quantity > 0}
        held_approved = sorted(held_symbols & self.season.approved_etfs)
        has_approved_etf = bool(held_approved)
        return RuleCheck(
            "approved_etf_minimum",
            RuleStatus.VERIFIED,
            has_approved_etf,
            (
                "At least one Approved-ETF-List holding is required. "
                + (
                    f"Satisfied: currently holding {held_approved} from the Approved ETF List."
                    if has_approved_etf
                    else "Not yet satisfied: no Approved-ETF-List holding in this account."
                )
            ),
        )

    def _minimum_trading_activity_check(self, today: date) -> RuleCheck:
        deadline = (
            self.season.minimum_activity_deadline if self.season else PROVISIONAL_ACTIVITY_DEADLINE
        )
        satisfied = self.budget.trades_used >= 1
        provisional_note = "" if self.season else " (PROVISIONAL deadline, 2025-26 season)"
        detail = (
            f"At least one executed trade is required by {deadline.isoformat()}"
            f"{provisional_note}. "
            + (
                "Satisfied: a trade has been recorded."
                if satisfied
                else "Not yet satisfied: no trade has been recorded yet."
            )
        )
        return RuleCheck(
            "minimum_trading_activity", RuleStatus.VERIFIED, satisfied, detail, deadline=deadline
        )

    def _commission_drag_check(self, account: AccountState) -> RuleCheck:
        equity = account.equity
        if equity <= 0:
            return RuleCheck(
                "commission_drag",
                RuleStatus.VERIFIED,
                True,
                (
                    f"Commission spent so far: ${self.budget.commission_spent:,.2f} "
                    f"({self.budget.trades_used} trades at PROVISIONAL "
                    f"${self.budget.commission_per_trade}/trade). Equity is not "
                    "positive, so drag as a percentage of equity is not "
                    "computable."
                ),
            )
        pct = self.budget.commission_drag_pct(equity)
        return RuleCheck(
            "commission_drag",
            RuleStatus.VERIFIED,
            True,
            (
                f"Commission spent so far: ${self.budget.commission_spent:,.2f} "
                f"on {self.budget.trades_used} trades (PROVISIONAL "
                f"${self.budget.commission_per_trade}/trade) is a {pct:.2f}% "
                f"drag on ${equity:,.2f} equity."
            ),
        )

    def _margin_and_shorting_check(self, account: AccountState) -> RuleCheck:
        problems = []
        if account.liabilities > 0:
            problems.append(
                f"margin liability of ${account.liabilities:,.2f} detected; "
                "Wharton bans margin outright"
            )
        shorts = sorted(pos.symbol for pos in account.positions if pos.quantity < 0)
        if shorts:
            problems.append(
                f"short position(s) detected in {', '.join(shorts)}; Wharton "
                "bans short selling outright"
            )
        if problems:
            return RuleCheck(
                "margin_and_shorting_ban",
                RuleStatus.VERIFIED,
                False,
                "VIOLATION: " + "; ".join(problems) + ". These are errors, not warnings.",
            )
        return RuleCheck(
            "margin_and_shorting_ban",
            RuleStatus.VERIFIED,
            True,
            "No margin liability and no short positions detected; margin and "
            "shorting are banned outright by the rules.",
        )

    # -- execution ----------------------------------------------------------

    def execution_note(self, today: date) -> str:
        """One line telling the student when and how orders will fill.

        Wharton is REAL TIME during market hours -- the opposite of DECA,
        which prices every fill at that session's close regardless of when
        the order was entered.
        """
        parts = [
            (
                "Wharton WInS executes REAL TIME during market hours "
                "(9:30a-4:00p ET); displayed prices lag the live tape by 10-15 "
                "minutes, after-hours orders fill at the next trading day's "
                "open, and international equities and bonds price end-of-day "
                "-- the opposite of DECA, which prices every fill at that "
                "session's close regardless of when the order was entered."
            )
        ]
        if today < TRADING_BEGINS:
            parts.append(f"Trading has not opened yet: it begins {TRADING_BEGINS.isoformat()}.")
        return " ".join(parts)

    def execution_note_lines(self, today: date) -> tuple[str, ...]:
        """The same content as `execution_note`, split into bullet lines for
        callers that want a multi-line rendering."""
        lines = [
            ("Wharton WInS is REAL TIME during market hours: live fills 9:30a-4:00p ET."),
            "Displayed prices lag the live tape by 10-15 minutes.",
            "Orders entered after-hours fill at the next trading day's open.",
            "International equities and bonds price end-of-day, not real time.",
            (
                "Contrast with DECA: DECA prices every fill at that session's "
                "close, regardless of when the order was entered."
            ),
        ]
        if today < TRADING_BEGINS:
            lines.append(f"Trading has not opened yet: it begins {TRADING_BEGINS.isoformat()}.")
        return tuple(lines)


def build_daily_plan(
    profile: WhartonProfile,
    account: AccountState,
    today: date,
    orders: tuple[SizedOrder, ...] = (),
    blocked: tuple[BlockedOrder, ...] = (),
    data_is_stale: bool = False,
    notes: tuple[str, ...] = (),
) -> DailyPlan:
    """Assemble the daily order sheet.

    In `WHARTON_UNVERIFIED`, every proposed order is withheld: it moves into
    `blocked` with `BlockReason.RULE_CONFLICT` naming the 2026-09-15
    release date, so a non-actionable plan is also an empty order sheet.
    Eligibility screening (`is_eligible`/`evaluate`) is unaffected and can
    still be called directly regardless of this gate.
    """
    rule_checks = profile.check_rules(account, today)
    emitted_orders = orders
    extra_blocked: tuple[BlockedOrder, ...] = ()

    if profile.season is None:
        extra_blocked = tuple(
            BlockedOrder(
                order.symbol,
                BlockReason.RULE_CONFLICT,
                (
                    f"{order.symbol}: no order sheet can be marked actionable "
                    "before the 2026-27 Wharton trading rules are released "
                    f"({MATERIALS_RELEASE.isoformat()}). Order withheld "
                    "pending verification."
                ),
            )
            for order in orders
        )
        emitted_orders = ()

    return DailyPlan(
        profile=profile.name,
        as_of=today,
        data_is_stale=data_is_stale,
        account=account,
        orders=emitted_orders,
        blocked=blocked + extra_blocked,
        rule_checks=tuple(rule_checks),
        notes=notes,
    )
